# Inference

Import Library

In [34]:
import pandas as pd
import pickle

Load Model

In [35]:
with open('model.pkl', 'rb') as file_1:
    model_model = pickle.load(file_1)

with open('scaler.pkl', 'rb') as file_2:
    model_scaler = pickle.load(file_2)

with open('pca.pkl', 'rb') as file_3:
    model_pca = pickle.load(file_3)

with open('list_cols.txt', 'rb') as file_4:
    list_col = pickle.load(file_4)

Load Data

In [36]:
data_in = {'CUST_ID': {0: 2253,
  1: 2672,
  2: 1415,
  3: 2234,
  4: 1680,
  5: 1015,
  6: 3941,
  7: 2284,
  8: 1228,
  9: 4461},
 'BALANCE': {0: 2674.65586389276,
  1: 1673.640374943755,
  2: 533.9526574483165,
  3: 1053.4867084202622,
  4: 3262.8928923655517,
  5: 1469.82145433601,
  6: 1691.312587958557,
  7: 1488.6155475598916,
  8: 2316.2248360238304,
  9: 2019.5763707993121},
 'BALANCE_FREQUENCY': {0: 0.5138978244086193,
  1: 1.0,
  2: 0.27093711969598844,
  3: 0.8365311460395684,
  4: 1.0,
  5: 0.6731759552750474,
  6: 0.8685585990133007,
  7: 1.0,
  8: 0.46320414938838694,
  9: 0.7426027800535182},
 'PURCHASES': {0: 961.9194719459942,
  1: 1155.7222509925184,
  2: 160.73964967007873,
  3: 1639.5058376616878,
  4: 1081.5827228251305,
  5: 923.8588094866808,
  6: 1903.9580970818763,
  7: 332.8948790742526,
  8: 1935.7758763324598,
  9: 739.1192742655526},
 'ONEOFF_PURCHASES': {0: 44.35923922146383,
  1: 668.8382054803036,
  2: 560.190722032616,
  3: 97.69278510065647,
  4: 669.2412219327013,
  5: 842.54640430866,
  6: 10.91635360626153,
  7: 159.9071486182084,
  8: 220.3463329998699,
  9: 625.0698399691834},
 'INSTALLMENTS_PURCHASES': {0: 485.039774171645,
  1: 767.069050816327,
  2: 630.2923104876082,
  3: 1207.3205752189333,
  4: 989.3355489290029,
  5: 1043.775737676651,
  6: 414.0285216143154,
  7: 976.4761687897314,
  8: 637.0737359006625,
  9: 788.2975184901586},
 'CASH_ADVANCE': {0: 540.087797983517,
  1: 916.1282484704399,
  2: 20.1666375201639,
  3: 589.4317836902818,
  4: 938.6041423548784,
  5: 1139.800082059398,
  6: 286.10469457445475,
  7: 1218.3417877701113,
  8: 649.0633566819586,
  9: 423.87982260694315},
 'PURCHASES_FREQUENCY': {0: 0.45201121517245624,
  1: 0.4728339058388259,
  2: 0.9950243343783814,
  3: 0.5595561931896882,
  4: 0.25016743359762716,
  5: 0.3760959318922431,
  6: 1.0,
  7: 0.7236147286282553,
  8: 1.0,
  9: 0.14747491811931102},
 'ONEOFF_PURCHASES_FREQUENCY': {0: 0.15616441210296084,
  1: 0.5331244945375393,
  2: 0.15912492989152616,
  3: 0.3848780737200027,
  4: 1.0,
  5: 0.973956081209606,
  6: 0.7444366984312304,
  7: 0.2624684505983741,
  8: 0.8355353743591802,
  9: 0.12029577713655581},
 'PURCHASES_INSTALLMENTS_FREQUENCY': {0: 0.28508788521030937,
  1: 0.2768193263360058,
  2: 0.6022538207357521,
  3: 0.36775028183638825,
  4: 0.8996991099639527,
  5: 0.5914746551686397,
  6: 0.989983165158958,
  7: 0.11096869036639512,
  8: 0.6769924599751934,
  9: 0.2909927989249469},
 'CASH_ADVANCE_FREQUENCY': {0: 0.31498964893028736,
  1: 0.527543976333128,
  2: 0.5686121244508957,
  3: 0.7750171104205146,
  4: 0.37069228215520544,
  5: 0.23674401920725907,
  6: 0.5525291615632986,
  7: 0.8456529042996053,
  8: 0.15005009132615932,
  9: 0.9357267402161191},
 'CASH_ADVANCE_TRX': {0: 4,
  1: 2,
  2: 2,
  3: 5,
  4: 2,
  5: 3,
  6: 2,
  7: 5,
  8: 4,
  9: 2},
 'PURCHASES_TRX': {0: 7,
  1: 15,
  2: 9,
  3: 9,
  4: 16,
  5: 5,
  6: 8,
  7: 6,
  8: 5,
  9: 10},
 'CREDIT_LIMIT': {0: 5000.0,
  1: 5000.0,
  2: 5848.2086346355645,
  3: 5000.0,
  4: 5000.0,
  5: 5000.0,
  6: 5000.0,
  7: 5000.0,
  8: 5000.0,
  9: 5000.0},
 'PAYMENTS': {0: 3673.676906598161,
  1: 4036.0253419516666,
  2: 4971.83559712393,
  3: 411.56812243067554,
  4: 2721.751906341724,
  5: 3561.0531970907728,
  6: 2618.675270262694,
  7: 4758.979012265072,
  8: 3240.4564365562615,
  9: 4596.017880554852},
 'MINIMUM_PAYMENTS': {0: 700,
  1: 1163.0261491070003,
  2: 700,
  3: 700,
  4: 613.0923808174831,
  5: 700,
  6: 700,
  7: 592.0757188692446,
  8: 700,
  9: 700},
 'PRC_FULL_PAYMENT': {0: 0.7122985901898896,
  1: 0.12818105011629788,
  2: 0.5414950384797022,
  3: 0.9021382422131542,
  4: 0.6717873905300129,
  5: 0.4429872678461668,
  6: 0.16291252894787955,
  7: 0.5694685046529278,
  8: 0.656411190562271,
  9: 0.7312490957033084},
 'TENURE': {0: 6,
  1: 6,
  2: 9,
  3: 5,
  4: 9,
  5: 9,
  6: 5,
  7: 6,
  8: 7,
  9: 7}}

Masukkan data dalam dataframe

In [37]:
data_in = pd.DataFrame(data_in)
data_in

,CUST_ID,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE
0,2253,2674.655864,0.513898,961.919472,44.359239,485.039774,540.087798,0.452011,0.156164,0.285088,0.314990,4,7,5000.000000,3673.676907,700.000000,0.712299,6
1,2672,1673.640375,1.000000,1155.722251,668.838205,767.069051,916.128248,0.472834,0.533124,0.276819,0.527544,2,15,5000.000000,4036.025342,1163.026149,0.128181,6
2,1415,533.952657,0.270937,160.739650,560.190722,630.292310,20.166638,0.995024,0.159125,0.602254,0.568612,2,9,5848.208635,4971.835597,700.000000,0.541495,9
3,2234,1053.486708,0.836531,1639.505838,97.692785,1207.320575,589.431784,0.559556,0.384878,0.367750,0.775017,5,9,5000.000000,411.568122,700.000000,0.902138,5
4,1680,3262.892892,1.000000,1081.582723,669.241222,989.335549,938.604142,0.250167,1.000000,0.899699,0.370692,2,16,5000.000000,2721.751906,613.092381,0.671787,9
5,1015,1469.821454,0.673176,923.858809,842.546404,1043.775738,1139.800082,0.376096,0.973956,0.591475,0.236744,3,5,5000.000000,3561.053197,700.000000,0.442987,9
6,3941,1691.312588,0.868559,1903.958097,10.916354,414.028522,286.104695,1.000000,0.744437,0.989983,0.552529,2,8,5000.000000,2618.675270,700.000000,0.162913,5
7,2284,1488.615548,1.000000,332.894879,159.907149,976.476169,1218.341788,0.723615,0.262468,0.110969,0.845653,5,6,5000.000000,4758.979012,592.075719,0.569469,6
8,1228,2316.224836,0.463204,1935.775876,220.346333,637.073736,649.063357,1.000000,0.835535,0.676992,0.150050,4,5,5000.000000,3240.456437,700.000000,0.656411,7
9,4461,2019.576371,0.742603,739.119274,625.069840,788.297518,423.879823,0.147475,0.120296,0.290993,0.935727,2,10,5000.000000,4596.017881,700.000000,0.731249,7

Seleksi kolom yang digunakan

In [38]:
# select columns
infer = data_in[list_col]

Scaling data

In [39]:
# scaling
infer_scaled = model_scaler.transform(infer)

Reduce dimensionality with PCA

In [40]:
infer_pca = model_pca.transform(infer_scaled)

Predict clusters with model

In [42]:
infer_final = model_model.predict(infer_pca)
infer_final

array([3, 1, 3, 3, 1, 3, 0, 4, 3, 3], dtype=int32)

Input cluster result into dataframe

In [43]:
# input default into inference dataframe
data_in["cluster"] = infer_final
data_in

,CUST_ID,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE,cluster
0,2253,2674.655864,0.513898,961.919472,44.359239,485.039774,540.087798,0.452011,0.156164,0.285088,0.314990,4,7,5000.000000,3673.676907,700.000000,0.712299,6,3
1,2672,1673.640375,1.000000,1155.722251,668.838205,767.069051,916.128248,0.472834,0.533124,0.276819,0.527544,2,15,5000.000000,4036.025342,1163.026149,0.128181,6,1
2,1415,533.952657,0.270937,160.739650,560.190722,630.292310,20.166638,0.995024,0.159125,0.602254,0.568612,2,9,5848.208635,4971.835597,700.000000,0.541495,9,3
3,2234,1053.486708,0.836531,1639.505838,97.692785,1207.320575,589.431784,0.559556,0.384878,0.367750,0.775017,5,9,5000.000000,411.568122,700.000000,0.902138,5,3
4,1680,3262.892892,1.000000,1081.582723,669.241222,989.335549,938.604142,0.250167,1.000000,0.899699,0.370692,2,16,5000.000000,2721.751906,613.092381,0.671787,9,1
5,1015,1469.821454,0.673176,923.858809,842.546404,1043.775738,1139.800082,0.376096,0.973956,0.591475,0.236744,3,5,5000.000000,3561.053197,700.000000,0.442987,9,3
6,3941,1691.312588,0.868559,1903.958097,10.916354,414.028522,286.104695,1.000000,0.744437,0.989983,0.552529,2,8,5000.000000,2618.675270,700.000000,0.162913,5,0
7,2284,1488.615548,1.000000,332.894879,159.907149,976.476169,1218.341788,0.723615,0.262468,0.110969,0.845653,5,6,5000.000000,4758.979012,592.075719,0.569469,6,4
8,1228,2316.224836,0.463204,1935.775876,220.346333,637.073736,649.063357,1.000000,0.835535,0.676992,0.150050,4,5,5000.000000,3240.456437,700.000000,0.656411,7,3
9,4461,2019.576371,0.742603,739.119274,625.069840,788.297518,423.879823,0.147475,0.120296,0.290993,0.935727,2,10,5000.000000,4596.017881,700.000000,0.731249,7,3

Terlihat bahwa data berhasil terbagi menjadi 4 cluster:
- 6 data masuk dalam cluster 3 yaitu 'Kelas Menengah, Transaksi Rendah'
- 2 data masuk dalam cluster 1 yaitu 'Kelas Atas, Transaksi Tinggi'
- 1 data masuk dalam cluster 0 yaitu 'Kelas Menengah, Transaksi Tinggi'
- 1 data masuk dalam cluster 4 yaitu 'Kelas Atas, Transaksi Rendah'